[package]
name = "token-duel"
version = "0.2.0"
description = "Token Duel — Anchor program for the Cocos Solana MWA demo"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "token_duel"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.31.1"
