//! On-chain state + PDA seed constants for Token Duel.

use anchor_lang::prelude::*;

/// Seed for the singleton protocol pool PDA. All forfeits flow in; all
/// tier-3 bonuses flow out. Pre-funded once via `initialize_pool`.
pub const POOL_SEED: &[u8] = b"pool";

/// Seed for a per-session PDA. Keyed by `[b"session", player, session_seed_u64]`.
/// The `session_seed` is generated by the client per play so that multiple
/// concurrent sessions don't collide, and `init` naturally rejects replay.
pub const SESSION_SEED: &[u8] = b"session";

/// Seed for the per-session SOL escrow. Keyed by `[b"escrow", session_pda]`.
/// Holds the staked SOL for the lifetime of a session.
pub const ESCROW_SEED: &[u8] = b"escrow";

pub const MIN_STAKE_LAMPORTS: u64 = 1_000_000;         // 0.001 SOL
pub const MAX_STAKE_LAMPORTS: u64 = 1_000_000_000;     // 1 SOL
pub const MAX_HEIGHT: u8 = 100;

#[account]
pub struct Session {
    pub player: Pubkey,       // 32 — the staker; enforced via has_one on settle
    pub amount: u64,          // 8  — stake in lamports
    pub session_seed: u64,    // 8  — client-chosen, stored so settle can re-derive PDA
    pub created_at: i64,      // 8  — unix timestamp from Clock sysvar
    pub settled: bool,        // 1  — guard against double-settle (belt-and-braces with close)
    pub bump: u8,             // 1  — session PDA bump
    pub escrow_bump: u8,      // 1  — escrow PDA bump
}

impl Session {
    /// Account data size (no 8-byte Anchor discriminator — that's added in `space`).
    pub const SPACE: usize = 32 + 8 + 8 + 8 + 1 + 1 + 1;
}

/// Seed for the singleton leaderboard PDA. Session 3 Phase B.
pub const LEADERBOARD_SEED: &[u8] = b"leaderboard";
/// Number of entries kept on-chain. Client also hardcodes 10 — keep in lockstep.
pub const LEADERBOARD_SIZE: usize = 10;

#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy, Default)]
pub struct LeaderboardEntry {
    pub player: Pubkey,  // 32
    pub height: u8,      // 1
    pub settled_at: i64, // 8
}

impl LeaderboardEntry {
    pub const SPACE: usize = 32 + 1 + 8; // 41
}

#[account]
pub struct Leaderboard {
    /// Ordered descending by height. Entries with `height == 0` are empty slots.
    /// First entry with a smaller height than `candidate` is the insertion point.
    pub entries: [LeaderboardEntry; LEADERBOARD_SIZE],
}

impl Leaderboard {
    /// Account data size (no 8-byte Anchor discriminator — that's added in `space`).
    /// 10 × 41 = 410.
    pub const SPACE: usize = LeaderboardEntry::SPACE * LEADERBOARD_SIZE;

    /// Insert candidate if it qualifies (strictly greater height than the
    /// lowest current entry). Shifts lower-ranked entries right and evicts
    /// the last one. No-op if `height == 0` or the candidate doesn't beat
    /// the tail. Returns Some(evicted_position) when an insert happened,
    /// None when the candidate didn't qualify.
    pub fn try_insert(&mut self, player: Pubkey, height: u8, settled_at: i64) -> Option<usize> {
        if height == 0 {
            return None;
        }
        // Find the first slot where the candidate beats the incumbent.
        // `height == 0` slots are zero-filled and act as sentinels at the
        // tail — any non-zero candidate wins there.
        let mut insert_at: Option<usize> = None;
        for i in 0..LEADERBOARD_SIZE {
            if self.entries[i].height < height || self.entries[i].height == 0 {
                insert_at = Some(i);
                break;
            }
        }
        let idx = insert_at?;
        // Shift from tail backwards to `idx+1`, dropping the last slot.
        for j in (idx + 1..LEADERBOARD_SIZE).rev() {
            self.entries[j] = self.entries[j - 1];
        }
        self.entries[idx] = LeaderboardEntry {
            player,
            height,
            settled_at,
        };
        Some(idx)
    }
}
